version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /examples/gasless
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /examples/sse
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /examples/tonapi-sdk
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /examples/websocket
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
